name = "OSRM"
uuid = "b59920ca-ae83-47b1-a52c-d6d89e4b4b86"
authors = ["Matt Bhagat-Conway <matt@indicatrix.org> and contributors"]
version = "0.1.0"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
